image: alpine

run pylint:
  stage: test
  script:
    - apk --no-cache add make py3-pip python3-dev gcc musl-dev libffi-dev openssl-dev
    - pip3 install -r requirements.txt
    - pip3 install -e .
    - python tests/run_pylint.py

create docs page:
  stage: deploy
  script:
    - apk --no-cache add make py3-pip python3-dev gcc musl-dev libffi-dev openssl-dev
    - pip3 install -r requirements.txt
    - pip3 install -e .
    - make html -C docs
    - mv docs/build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - tags

publish to pypi:
  stage: deploy
  script:
    - apk --no-cache add make py3-pip python3-dev gcc musl-dev libffi-dev openssl-dev
    - pip3 install twine
    - python setup.py sdist
    - twine upload dist/*
  artifacts:
    paths:
      - dist
  only:
    - tags
